### ISSUE TITLE
Apply devise gem and create a login page and home page after logged in

### ISSUE THREAD

**Issue by joko3ono** [virtualspirit/training-property#1]
Login and Signup page lets just use the one that devise generated for us.

Home page :
![before_login](https://user-images.githubusercontent.com/1142773/56010784-3f55f000-5d0f-11e9-924b-8059e10c5dfa.png)

and after user logged in show simillar home page with different header.

![after_login](https://user-images.githubusercontent.com/1142773/56010813-5c8abe80-5d0f-11e9-83bc-f14b65b54f36.png)

requirements :
1. after login the `Hello (UserName)` should be dropdown with logout link.
2. for the product image just use static image for now, lets use this https://via.placeholder.com/150

**Comment by cloudsbird** [comment]
Can i use bootstrap?

**Comment by cloudsbird** [comment]
Finished
