### ISSUE TITLE
Integrate theme

### ISSUE THREAD

**Issue by nichthinkof30** [virtualspirit/training-property#3]
https://github.com/puikinsh/Adminator-admin-dashboard

Please integrate this into the app, functional features to be done

- [x] Sign up
- [x] Sign In
- [x] Dashboard -> Show Calendar Page
- [x] View Property in table
- [x] CRUD Property in table

Sidebar:
1. Dashboard
2. Property

Remove/hide all unnecessary features in the theme template.

Follow the components in the theme template. 

@joko3ono please assist on best practice to integrate a theme template.

Deadline: 3 days.

**Comment by cloudsbird** [comment]
Upload and Delete still in issues because of parent and child, will try to fix it soon.
